version: '3.8'

services:
  fastapi-app:
    build: .
    container_name: pod
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./temp_uploads:/app/temp_uploads
      - ./google_credentials.json:/app/google_credentials.json:ro
    restart: unless-stopped

