version: '3.8'

services:
  fastapi-app:
    build: .
    container_name: malachite
    ports:
      - "9000:9000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./temp_uploads:/app/temp_uploads
      - ./google_credentials.json:/app/google_credentials.json:ro
    restart: unless-stopped

nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app